name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: project-grupp-5-1

    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Backend/Backend.csproj --configuration Release
    - name: Test
      run: dotnet test ./XUnitTest/XUnitTestBackend.csproj --configuration Release

