name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



    
jobs:
  build-job:
    
    runs-on: ubuntu-latest
    
    defaults:
     run:
      working-directory: Backend

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./Project.sln --configuration Release

      
  test-job:
    
    runs-on: ubuntu-latest
    
    defaults:
     run:
      working-directory: XUnitTestBackend

    steps:
     - name: Test
       run: dotnet test ./Project.sln --configuration Release
