name: grupp5storeback

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  AZURE_WEBAPP_NAME: grupp5store 
  ASURE_WEBAPP_PACKAGE_PATH: './backend/published'
  NETCORE_VERSION:  '3.1.301'


jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Publish
      run: dotnet publish --configuration Release --no-build -output ${{ env.ASURE_WEBAPP_PACKAGE_PATH }}

    - name: "Deploy to Azure WebApp"
      uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH }}
          package: ${{ env.ASURE_WEBAPP_PACKAGE_PATH }}
