name: FrontendTest

on:
  push:
    branches: [ develop ]
    
jobs:
  
  
  build:
    runs-on: ubuntu-latest
    
    # continues integration (build + test)
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Frontend
    
    - name: Test
      run: dotnet test ./XUnitTestFrontend/XUnitTestFrontend.csproj
      
    # continues deployment (build image and push to acr)
    - name: Login to container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Create Docker-image and push to ACR
      run: |
        docker build ./Frontend/ -t ${{ secrets.ACR_LOGIN_SERVER }}/fetest:${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/fetest:${{ github.sha }}
    
    - name: Login to Azure CLI 
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy and run Client on webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: storefront5test
        publish-profile: ${{ secrets.FRONTENDTEST_PUBLISH_PROFILE }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/fetest:${{ github.sha }}    
    
    
